#################################
# Development
#################################
FROM beevelop/ionic:latest as build

# Create app folder
RUN mkdir /app
WORKDIR /app

ENV IONIC_VERSION 4.10.4

# Install app dependencies
RUN apt-get update && apt-get install -y git bzip2 openssh-client && \
    npm i -g --unsafe-perm ionic@${IONIC_VERSION} && \
    ionic --no-interactive config set -g daemon.updates false && \
    rm -rf /var/lib/apt/lists/* && apt-get clean

# Add configuration files
COPY image-files/ /
RUN chmod 700 /usr/local/bin/docker-entrypoint-dev.sh

# Expose port 8100
EXPOSE 8100
ENTRYPOINT ["docker-entrypoint-dev.sh"]
